// `npm run dev:backend` (#135): a local Supabase in Docker with the current
// schema and a seeded dev user, so the app runs without production data.
//
//   1. `supabase start` (Supabase CLI, npm devDependency; needs Docker)
//   2. apply supabase/schema.sql (idempotent) + reload the PostgREST cache
//   3. write .env.local pointing the app at the local stack
//   4. seed dev@tatu.local from samples/*.csv (scripts/seed-local.ts)
//
// Safe to re-run: schema.sql is idempotent, the user is created once, and the
// seed only inserts transactions that aren't on the server yet.
// Stop the stack with `npx supabase stop`.

import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
// supabase_db_<project_id>; project_id is pinned in supabase/config.toml.
const DB_CONTAINER = 'supabase_db_tatu'
const ENV_FILE = join(ROOT, '.env.local')
const ENV_MARKER = '# Generated by `npm run dev:backend`'
const DEV_SERVER_URL = 'http://localhost:5173'

function fail(message) {
  console.error(`\ndev:backend: ${message}`)
  process.exit(1)
}

function step(message) {
  console.log(`\n==> ${message}`)
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    stdio: 'inherit',
    ...options,
  })
  if (result.error) fail(`${command} failed: ${result.error.message}`)
  if (result.status !== 0) {
    fail(`\`${command} ${args.join(' ')}\` exited with ${result.status}`)
  }
  return result
}

function supabaseStatus() {
  const result = run('npx', ['supabase', 'status', '-o', 'json'], {
    stdio: ['ignore', 'pipe', 'inherit'],
    encoding: 'utf8',
  })
  // The CLI may print notices before the JSON object.
  const json = result.stdout.slice(result.stdout.indexOf('{'))
  const status = JSON.parse(json)
  const url = status.API_URL
  const publishableKey = status.PUBLISHABLE_KEY ?? status.ANON_KEY
  const serviceRoleKey = status.SERVICE_ROLE_KEY ?? status.SECRET_KEY
  if (!url || !publishableKey || !serviceRoleKey) {
    fail(`unexpected \`supabase status\` output: ${Object.keys(status)}`)
  }
  return { url, publishableKey, serviceRoleKey, studioUrl: status.STUDIO_URL }
}

function applySchema() {
  const schema = readFileSync(join(ROOT, 'supabase', 'schema.sql'), 'utf8')
  run(
    'docker',
    [
      'exec',
      '-i',
      DB_CONTAINER,
      'psql',
      '--quiet',
      '-v',
      'ON_ERROR_STOP=1',
      '-U',
      'postgres',
      '-d',
      'postgres',
    ],
    {
      input: `set client_min_messages = warning;\n${schema}\nnotify pgrst, 'reload schema';\n`,
      stdio: ['pipe', 'ignore', 'inherit'],
    }
  )
}

// PostgREST reloads its schema cache asynchronously after the notify.
async function waitForTransactionsTable({ url, publishableKey }) {
  for (let attempt = 0; attempt < 30; attempt++) {
    const response = await fetch(
      `${url}/rest/v1/transactions?select=transaction_id&limit=0`,
      { headers: { apikey: publishableKey } }
    ).catch(() => null)
    if (response?.ok) return
    await new Promise((resolve) => setTimeout(resolve, 500))
  }
  fail('PostgREST never exposed public.transactions after applying schema')
}

function writeEnvLocal({ url, publishableKey }) {
  if (existsSync(ENV_FILE)) {
    const current = readFileSync(ENV_FILE, 'utf8')
    if (!current.startsWith(ENV_MARKER)) {
      fail(
        '.env.local exists and was not written by this script. Move it ' +
          'aside (it may point at a real project) and re-run.'
      )
    }
  }
  const lines = [
    ENV_MARKER,
    '# Points the app at the LOCAL Supabase stack. Delete this file to go back',
    '# to the project configured in .env. Never put production keys here.',
    `VITE_SUPABASE_URL=${url}`,
    `VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${publishableKey}`,
    `VITE_SUPABASE_PASSWORD_RESET_REDIRECT_URL=${DEV_SERVER_URL}`,
    '# Blank on purpose: no Firebase analytics from local runs.',
    'VITE_FIREBASE_API_KEY=',
    'VITE_FIREBASE_AUTH_DOMAIN=',
    'VITE_FIREBASE_PROJECT_ID=',
    'VITE_FIREBASE_APP_ID=',
    '',
  ]
  writeFileSync(ENV_FILE, lines.join('\n'))
}

async function main() {
  step('Checking Docker')
  run('docker', ['info'], { stdio: 'ignore' })

  step('Starting local Supabase (first run pulls images, takes a while)')
  run('npx', ['supabase', 'start'])
  const status = supabaseStatus()

  step('Applying supabase/schema.sql')
  applySchema()
  await waitForTransactionsTable(status)

  step('Writing .env.local')
  writeEnvLocal(status)

  step('Seeding dev@tatu.local from samples/*.csv')
  run('npx', ['vite-node', 'scripts/seed-local.ts'], {
    env: {
      ...process.env,
      // Explicit so the seed can't pick up a remote project from .env.
      VITE_SUPABASE_URL: status.url,
      VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY: status.publishableKey,
      SUPABASE_SERVICE_ROLE_KEY: status.serviceRoleKey,
    },
  })

  console.log(`
Local backend ready.
  API      ${status.url}
  Studio   ${status.studioUrl ?? '(disabled)'}
  Login    dev@tatu.local / tatu-dev-password
Next: npm run dev  ->  ${DEV_SERVER_URL}
Stop:  npx supabase stop`)
}

main()
